### ISSUE TITLE
DailyTemperatureにdateを追加

### ISSUE THREAD

**Issue by Joharu** [Joharu/g-assignment#18]
#Why
created_at はあくまでcreated_atなので、日付用のカラムを追加した方が良い

#TODO
- [x] rake db:reset
- [x] DB migration file作成
- [x] db:seed file の編集
- [x] rake db:seed
